"""Diagnostic outcomes from fact_conditions."""

from __future__ import annotations

from typing import Any

from api.bq import fq, run_query

_ATTRIBUTION = "Documented on patient chart — not generated by SwiftCare AI"


def list_conditions(patient_id: str, active_only: bool = True) -> list[dict[str, Any]]:
    sql = f"""
SELECT
  condition_id,
  patient_id,
  COALESCE(condition_desc, condition_code, 'Condition') AS display_name,
  CASE WHEN is_active THEN 'active' ELSE 'inactive' END AS status,
  CAST(onset_date AS STRING) AS onset_date
FROM {fq("swiftcare_fhir_analytics", "fact_conditions")}
WHERE patient_id = @patient_id
  AND (@active_only = FALSE OR is_active = TRUE)
ORDER BY onset_date DESC
"""
    rows, _, _ = run_query(
        sql, {"patient_id": patient_id, "active_only": active_only}
    )
    for row in rows:
        row["source"] = "chart"
        row["attribution"] = _ATTRIBUTION
    return rows
