"""Source-recorded FHIR chart findings for the patient workspace."""

from __future__ import annotations

from typing import Any

from api.bq import fq, run_query


def list_fhir_clinical_findings(patient_id: str) -> list[dict[str, Any]]:
    """Return FHIR conditions and symptom-relevant observations without relabeling them.

    Synthea's FHIR cohort does not include a separate Symptom resource.  Active
    Conditions and observations such as pain scores are therefore displayed as
    source-recorded chart findings, distinct from operational symptoms entered
    by staff in ``swiftcare_ops.patient_symptoms``.
    """
    sql = f"""
WITH findings AS (
  SELECT
    CONCAT('condition:', condition_id) AS finding_id,
    patient_id,
    COALESCE(condition_desc, condition_code, 'Condition') AS display_name,
    'FHIR Condition' AS source_kind,
    CAST(onset_date AS STRING) AS recorded_date,
    NULL AS value_text
  FROM {fq("swiftcare_fhir_analytics", "fact_conditions")}
  WHERE patient_id = @patient_id AND is_active = TRUE

  UNION ALL

  SELECT
    CONCAT('observation:', observation_id) AS finding_id,
    patient_id,
    COALESCE(observation_desc, observation_code, 'Observation') AS display_name,
    'FHIR Observation' AS source_kind,
    CAST(observation_date AS STRING) AS recorded_date,
    COALESCE(value_string, CAST(ROUND(value_numeric, 2) AS STRING), 'Recorded') AS value_text
  FROM {fq("swiftcare_fhir_analytics", "fact_observations")}
  WHERE patient_id = @patient_id
    AND (
      REGEXP_CONTAINS(LOWER(COALESCE(observation_desc, '')), r'(pain|symptom)')
      OR category = 'survey'
    )
)
SELECT * FROM findings
ORDER BY recorded_date DESC
LIMIT 12
"""
    rows, _, _ = run_query(sql, {"patient_id": patient_id})
    for row in rows:
        row["attribution"] = "Source-recorded FHIR chart data — not generated by SwiftCare AI"
    return rows
